create table veiculo (
	id BIGINT generated by default as identity not null, 
    proprietario_id BIGINT not null,
	marca VARCHAR(20) not null, 
	modelo VARCHAR(20) not null, 
	placa VARCHAR(7) not null,
    status VARCHAR(20) not null,
    data_cadastro TIMESTAMP not null, 
	data_apreensao TIMESTAMP,
  
	primary key (id)
);

alter table veiculo add constraint fk_veiculo_proprietario
foreign key (proprietario_id) references proprietario (id);

alter table veiculo add constraint uk_veiculo unique (placa);









