create table autuacao (
	id BIGINT generated by default as identity not null, 
  	veiculo_id BIGINT not null,
	descricao TEXT not null, 
	valor_multa DECIMAL(10,2) not null, 
  	data_ocorrencia TIMESTAMP not null, 
  
	primary key (id)
);

alter table autuacao add constraint fk_autuacao_veiculo
foreign key (veiculo_id) references veiculo (id);